import type { Guest } from "./types";

export const guests: Guest[] = [
	// Stół pary młodej
	{ firstName: "Mikołaj", lastName: "Hirsz", table: 1, seat: 4 },
	{ firstName: "Wiktoria", lastName: "Wróblewska", table: 1, seat: 3 },
	{ firstName: "Damian", lastName: "Drewing", table: 1, seat: 1 },
	{ firstName: "Magdalena", lastName: "Drewing", table: 1, seat: 2 },
	{ firstName: "Dominik", lastName: "Kitowski", table: 1, seat: 5 },

	// Goście Pana Młodego
	{ firstName: "Tadeusz", lastName: "Hirsz", table: 3, seat: 1 },
	{ firstName: "Dorota", lastName: "Hirsz", table: 3, seat: 2 },
	{ firstName: "Patryk", lastName: "Klejna", table: 3, seat: 3 },
	{ firstName: "Alina", lastName: "Klejna", table: 3, seat: 4 },
	{ firstName: "Krzysztof", lastName: "Hirsz", table: 3, seat: 5 },
	{ firstName: "Martyna", lastName: "Borecka", table: 3, seat: 6 },
	{ firstName: "Elżbieta", lastName: "Hirsz", table: 3, seat: 7 },
	{ firstName: "Irena", lastName: "Leszczyńska", table: 3, seat: 8 },
	{ firstName: "Sylwia", lastName: "Sroga", table: 3, seat: 9 },
	{ firstName: "Karol", lastName: "Krefft", table: 3, seat: 10 },
	{ firstName: "Gerard", lastName: "Krefft", table: 3, seat: 11 },
	{ firstName: "Teresa", lastName: "Krefft", table: 3, seat: 12 },

	{ firstName: "Piotr", lastName: "Hirsz", table: 3, seat: 13 },
	{ firstName: "Jagoda", lastName: "Piotrowska-Hirsz", table: 3, seat: 14 },
	{ firstName: "Janusz", lastName: "Leszczyński", table: 3, seat: 15 },
	{ firstName: "Bożena", lastName: "Leszczyńska", table: 3, seat: 16 },
	{ firstName: "Krzysztof", lastName: "Żaczek", table: 3, seat: 17 },
	{ firstName: "Sabina", lastName: "Żaczek", table: 3, seat: 18 },
	{ firstName: "Karol", lastName: "Leszczyński", table: 3, seat: 19 },
	{ firstName: "Anna", lastName: "Leszczyńska", table: 3, seat: 20 },
	{ firstName: "Michał", lastName: "Krefft", table: 3, seat: 21 },
	{ firstName: "Iwona", lastName: "Krefft", table: 3, seat: 22 },
	{ firstName: "Filip", lastName: "Krefft", table: 3, seat: 23 },
	{ firstName: "Sabina", lastName: "Hirsz", table: 3, seat: 24 },

	{ firstName: "Rafał", lastName: "Żaczek", table: 5, seat: 1 },
	{ firstName: "Marta", lastName: "Karwowska", table: 5, seat: 2 },
	{ firstName: "Karol", lastName: "Labuda", table: 5, seat: 3 },
	{ firstName: "Alicja", lastName: "Leszczyńska", table: 5, seat: 4 },
	{ firstName: "Michał", lastName: "Piotrowski", table: 5, seat: 5 },
	{ firstName: "Maja", lastName: "Piotrowska", table: 5, seat: 6 },
	{ firstName: "Maja", lastName: "Hirsz", table: 5, seat: 7 },
	{ firstName: "Nikodem", lastName: "Kotkowski", table: 5, seat: 8 },
	{ firstName: "Aleksandra", lastName: "Kosznik", table: 5, seat: 9 },
	{ firstName: "Maksymilian", lastName: "Zarach", table: 5, seat: 10 },
	{ firstName: "Wiktoria", lastName: "Kuczkowska", table: 5, seat: 11 },
	{ firstName: "Mateusz", lastName: "Cibor", table: 5, seat: 12 },
	{ firstName: "Oliwia", lastName: "Wrona", table: 5, seat: 13 },
	
	{ firstName: "Robert", lastName: "Żaczek", table: 5, seat: 14 },
	{ firstName: "Marcin", lastName: "Rychert", table: 5, seat: 15 },
	{ firstName: "Zuzanna", lastName: "Leszczyńska", table: 5, seat: 16 },
	{ firstName: "Osoba towarzysząca", lastName: "Julii Leszczyńskiej", table: 5, seat: 17 },
	{ firstName: "Julia", lastName: "Leszczyńska", table: 5, seat: 18 },
	{ firstName: "Adrian", lastName: "Leszczyński", table: 5, seat: 19 },
	{ firstName: "Martyna", lastName: "Labuda", table: 5, seat: 20 },
	{ firstName: "Kryspin", lastName: "Sznejkowski", table: 5, seat: 21 },
	{ firstName: "Rozalia", lastName: "Kitowska", table: 5, seat: 22 },
	{ firstName: "Jakub", lastName: "Pierzchalski", table: 5, seat: 23 },
	{ firstName: "Kamil", lastName: "Konkol", table: 5, seat: 24 },
	{ firstName: "Anna", lastName: "Kozielska", table: 5, seat: 25 },

	// Goście Panny Młodej
	{ firstName: "Marcin", lastName: "Wróblewski", table: 2, seat: 1 },
	{ firstName: "Adriana", lastName: "Wróblewska", table: 2, seat: 2 },
	{ firstName: "Łukasz", lastName: "Wróblewski", table: 2, seat: 3 },
	{ firstName: "Karolina", lastName: "Wróblewska", table: 2, seat: 4 },
	{ firstName: "Piotr", lastName: "Pryczkowski", table: 2, seat: 5 },
	{ firstName: "Żaneta", lastName: "Pryczkowska", table: 2, seat: 6 },
	{ firstName: "Krzysztof", lastName: "Wiśniewski", table: 2, seat: 7 },
	{ firstName: "Wioleta", lastName: "Wiśniewska", table: 2, seat: 8 },
	{ firstName: "Kamil", lastName: "Terman", table: 2, seat: 9 },
	{ firstName: "Oliwia", lastName: "Terman", table: 2, seat: 10 },
	{ firstName: "Łukasz", lastName: "Wróblak", table: 2, seat: 11 },
	{ firstName: "Ilona", lastName: "Wróblak", table: 2, seat: 12 },

	{ firstName: "Radosław", lastName: "Rutkiewicz", table: 2, seat: 13 },
	{ firstName: "Beata", lastName: "Rutkiewicz", table: 2, seat: 14 },
	{ firstName: "Łukasz", lastName: "Lichnerowicz", table: 2, seat: 15 },
	{ firstName: "Małgorzata", lastName: "Lichnerowicz", table: 2, seat: 16 },
	{ firstName: "Marcin", lastName: "Ramczyk", table: 2, seat: 17 },
	{ firstName: "Kamila", lastName: "Ramczyk", table: 2, seat: 18 },
	{ firstName: "Władysław", lastName: "Wróblewski", table: 2, seat: 19 },
	{ firstName: "Maria", lastName: "Wróblewska", table: 2, seat: 20 },
	{ firstName: "Mirosława", lastName: "Komkowska", table: 2, seat: 21 },
	{ firstName: "Michał", lastName: "Śledzik", table: 2, seat: 22 },
	{ firstName: "Martyna", lastName: "Śledzik", table: 2, seat: 23 },

	{ firstName: "Piotr", lastName: "Chrapkowski", table: 4, seat: 1 },
	{ firstName: "Julia", lastName: "Chrapkowska", table: 4, seat: 2 },
	{ firstName: "Bartosz", lastName: "Różański", table: 4, seat: 3 },
	{ firstName: "Laura", lastName: "Wróblewska", table: 4, seat: 4 },
	{ firstName: "Filip", lastName: "Wróblewski", table: 4, seat: 5 },
	{ firstName: "Lena", lastName: "Pryczkowska", table: 4, seat: 6 },
	{ firstName: "Max", lastName: "Lichnerowicz", table: 4, seat: 7 },
	{ firstName: "Albert", lastName: "Wróblewski", table: 4, seat: 8 },
	{ firstName: "Oliwia", lastName: "", table: 4, seat: 9 },

	{ firstName: "Maksymilian", lastName: "Płotka", table: 4, seat: 11 },
	{ firstName: "Dominika", lastName: "Chrapkowska", table: 4, seat: 12 },
	{ firstName: "Dawid", lastName: "Raczkowski", table: 4, seat: 13 },
	{ firstName: "Aleksandra", lastName: "Pietrzak", table: 4, seat: 14 },
	{ firstName: "Maja", lastName: "Rutkiewicz", table: 4, seat: 15 },
	{ firstName: "Igor", lastName: "Rutkiewicz", table: 4, seat: 16 },
	{ firstName: "Alicja", lastName: "Gurzyńska", table: 4, seat: 17 },
	{ firstName: "Maksym", lastName: "Śledzik", table: 4, seat: 18 },
	{ firstName: "Ewa", lastName: "Słomska", table: 4, seat: 19 },
];